[submitter]
name = "Benji377"
email = "name@domain.com"
website = "https://website.com"
is_maintainer = false

[package]
name = "discord"
version = "0.0.53"
summary = "The Discord app for Debian"
description = ""
type = "SocialNetworking"
website = "https://discord.com"
license = "proprietary"
source = "https://dl.discordapp.net/apps/linux/$pversion/$pname-$pversion.deb"
auto_update = true
arch = "x86_64"

[assets]
logo = ""
banner = ""
