# Information related to the maintainer/submitter
[submitter]
name = "Benji377"
email = "raspirus.dev@gmail.com"
website = "https://github.com/Benji377"
is_maintainer = true

# Data related to the package
[package]
name = "raspirus"
version = "1.1.3"
summary = "Lightweight hash-based virusscanner"
description = "Raspirus is your cost-free, versatile malware scanner. Tailored signature detection, comprehensive file scans, and privacy prioritized for swift, reliable protection."
type = "DeveloperTool"
website = "https://raspirus.deno.dev"
license = "GPL-3.0-only"
# Needs to be a .deb file
source = "https://github.com/Raspirus/Raspirus/releases/download/v$pversion/$pname_$pversion_amd64.deb"
auto_update = false
# Adapt to correct nomenclature
arch = "x86_64"
signature = "e185ad933dc35ba571ba614142420002009e6688266947b15ee6316905372b83" # sha256 Use `sha256sum <package.deb>`

[assets]
# URLs to public images. Will resize automatically
logo = "https://raw.githubusercontent.com/Raspirus/media/main/logo.png"
banner = "https://raw.githubusercontent.com/Raspirus/media/main/banner.png"