name: Package Update

on:
  schedule:
  - cron: "0 13 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install lintian

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python script.py update

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updating package list'
          add: '-A'
