name: Package Verify

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'specifications/*.toml'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install lintian
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: specifications/*.toml

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          FIRST_CHANGED_FILE=$(echo "${ALL_CHANGED_FILES}" | head -n 1)
          echo "changed_file=$FIRST_CHANGED_FILE" >> "$GITHUB_ENV"
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python script.py verify $changed_file

      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fs.readFileSync('verification.txt', 'utf8')
            })
