name: Package Fetch

on:
  push:
    branches: [ "main" ]
    paths:
      - 'specifications/*.toml'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python script.py fetch

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Fetched remaining packages'
          add: '-A'
