name: Package Verify

on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches: ["main"]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          FIRST_CHANGED_FILE=$(echo "${ALL_CHANGED_FILES}" | head -n 1)
          echo "::set-output name=first_changed_file::$FIRST_CHANGED_FILE"
        
      - name: Echo stored variable
        run: |
          echo "The first changed file is: ${{ steps.first-changed-file.outputs.first_changed_file }}"

      
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
